#!/usr/bin/env bash
set -euo pipefail
[[ "${DOKKU_TRACE:-}" == "1" ]] && set -x

PLUGIN_ROOT="$(cd "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")" && pwd)"
# shellcheck source=config
source "$PLUGIN_ROOT/config"
# shellcheck source=functions
source "$PLUGIN_ROOT/functions"

shift || true

service_list
